### ISSUE TITLE
Replace jest-fast-check with @fast-check/jest

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/wesnoth-map-diff#36]
Both `npm` and `yarn` warn about `jest-fast-check` being deprecated in favor of `@fast-check/jest`. However, attempting to actually switch to it results in CI failures, as can be seen in 96f8dc484e0d2374835ce3bc17002c39d58f3451.

**Comment by cooljeanius** [comment]
> However, attempting to actually switch to it results in CI failures, as can be seen in [96f8dc4](https://github.com/cooljeanius/wesnoth-map-diff/commit/96f8dc484e0d2374835ce3bc17002c39d58f3451).

...specifically, the failures are:
```
> jest

FAIL tests/rootByTagName.test.ts
  ● Test suite failed to run

    Cannot find module 'jest-fast-check' from 'tests/rootByTagName.test.ts'

    > 1 | import { testProp, fc } from 'jest-fast-check'
        | ^
      2 | import type { WmlParsed } from '../src/wml/parser'
      3 | import rootByTagName from '../src/wml/rootByTagName'
      4 | import { wmlName } from './arbitraries'

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (tests/rootByTagName.test.ts:1:1)

FAIL tests/parser.test.ts
  ● Test suite failed to run

    Cannot find module 'jest-fast-check' from 'tests/parser.test.ts'

    > 1 | import { testProp, fc } from 'jest-fast-check'
        | ^
      2 | import { parseWml } from '../src/wml/parser'
      3 | import { wmlName, fullAttributeUnmapper, fullAttribute, fullAttributeString, fullAttributeStringUnmapper } from './arbitraries'
      4 |

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (tests/parser.test.ts:1:1)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.913 s
Ran all test suites.
Error: Process completed with exit code 1.
```
cc @macabeus

**Comment by macabeus** [comment]
Did you try to replace
```
import { testProp, fc } from 'jest-fast-check'
```
with
```
import { testProp, fc } from '@fast-check/jest'
```
?

**Comment by cooljeanius** [comment]
> Did you try to replace
> 
> ```
> import { testProp, fc } from 'jest-fast-check'
> ```
> 
> with
> 
> ```
> import { testProp, fc } from '@fast-check/jest'
> ```
> 
> ?

Just tried that, now the failure is:
```
$ npm run test

> wesnoth-map-diff@0.0.3 test
> jest

 FAIL  tests/rootByTagName.test.ts
  ● #RootByTagName › when has only one tag › includes it on the rooted object (with seed=1703647664110)

    Unexpected value received: not an instance of Arbitrary

      at assertIsArbitrary (node_modules/@fast-check/jest/node_modules/fast-check/lib/check/arbitrary/definition/Arbitrary.js:210:15)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/@fast-check/jest/lib/jest-fast-check.js:22:28)

  ● #RootByTagName › when has two tags › with the same name › merge it on the rooted object (with seed=1703647664111)

    Unexpected value received: not an instance of Arbitrary

      at assertIsArbitrary (node_modules/@fast-check/jest/node_modules/fast-check/lib/check/arbitrary/definition/Arbitrary.js:210:15)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/@fast-check/jest/lib/jest-fast-check.js:22:28)

 FAIL  tests/parser.test.ts
  ● Test suite failed to run

    fc.oneof expects arbitraries to be specified

      129 |   describe('when tag is not closed', () => {
      130 |     describe('because of missing the the closed one', () => {
    > 131 |       testProp('raises an error', [wmlName(), fc.oneof(fullAttribute(), fullAttributeString(), fc.constant(''))], (tagName, tagBody) => {
          |                                                  ^
      132 |         const source = `
      133 |           [${tagName}]
      134 |             ${tagBody}

      at Function.from (node_modules/@fast-check/jest/node_modules/fast-check/lib/arbitrary/_internals/FrequencyArbitrary.js:25:23)
      at oneof (tests/parser.test.ts:131:50)
      at describe (tests/parser.test.ts:130:5)
      at describe (tests/parser.test.ts:129:3)
      at Object.describe (tests/parser.test.ts:5:1)

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        2.132 s
Ran all test suites.
```

**Comment by macabeus** [comment]
That's probably breaking changes on the package.
Try use the same version
